This is makeindex, version 2.15 [MiKTeX 21.3].
Scanning style file ./template.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file template.acn....done (15 entries accepted, 0 rejected).
Sorting entries....done (63 comparisons).
Generating output file template.acr....done (18 lines written, 0 warnings).
Output written in template.acr.
Transcript written in template.alg.
